version: '3.1'
services:
  tangsengdaodaomanager:  # 唐僧叨叨的后台管理系统
    image: tsddmanager:latest
    restart: always
    environment:
      - API_URL=http://tangsengdaodaoserver:8090/
    ports:
      - "83:80"
    # 修正：移除 condition: service_healthy