version: '3.1'
services:
  mysql:  # mysql数据库
    image: registry.cn-shanghai.aliyuncs.com/wukongim/mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    volumes:
      - ./mysqldata:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
  
  adminer:  # mysql web管理工具 调试用
    image: registry.cn-shanghai.aliyuncs.com/wukongim/adminer:latest
    ports:
      - 8306:8080
    depends_on:
      - mysql